# Generated by Django 4.1 on 2023-02-28 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="create_date",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 0, 57, 10, 355724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 28, 0, 57, 10, 355724, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
