# Generated by Django 4.1 on 2023-03-02 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_comment_create_date_remove_post_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 2, 22, 20, 43, 877592, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 2, 22, 20, 43, 876591, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
