# Generated by Django 4.1 on 2023-03-02 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_created_date_alter_post_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 2, 23, 58, 19, 305354, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 2, 23, 58, 19, 305354, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
